# Generated by Django 6.0.4 on 2026-04-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqueue',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'ยังไม่ชำระเงิน'), ('paid', 'ชำระเงินแล้ว')], default='pending', max_length=20),
        ),
    ]
