# Generated by Django 6.0.4 on 2026-04-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_orderqueue_payment_method_orderqueue_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='drink_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sweetness',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='discount_used',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
