# Generated by Django 6.0.4 on 2026-04-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='boba',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flavor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
